"""
Tests for zip-wrapped PyTorch checkpoint support (torch.save()'s default
format since PyTorch 1.6). Fixtures generated by
scripts/generate_torch_zip_fixtures.py -- a real zip archive containing a
data.pkl member, no PyTorch installation required to produce or scan it.
"""

from pathlib import Path

from mlscan.detect import detect_format_from_content, format_from_extension
from mlscan.report import Severity
from mlscan.scanners.pickle_scanner import scan_pickle

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"


def test_benign_zip_checkpoint_has_no_findings():
    findings = scan_pickle(FIXTURES_DIR / "benign" / "benign_torch_checkpoint.pt")
    assert findings == []


def test_malicious_zip_checkpoint_is_flagged_critical():
    findings = scan_pickle(FIXTURES_DIR / "malicious" / "zip_wrapped_reduce_os_system.pt")
    assert len(findings) == 1
    assert findings[0].severity == Severity.CRITICAL
    assert findings[0].rule_id == "PICKLE_DANGEROUS_REDUCE"


def test_content_detection_recognizes_zip_wrapped_checkpoint_as_pickle():
    path = FIXTURES_DIR / "malicious" / "zip_wrapped_reduce_os_system.pt"
    assert format_from_extension(path) == "pickle"
    assert detect_format_from_content(path) == "pickle"


def test_content_detection_catches_zip_checkpoint_renamed_to_onnx(tmp_path):
    # Same evasion class we already defend against for plain pickles:
    # renaming a malicious zip-wrapped checkpoint to a .onnx extension
    # must not skip pickle scanning.
    disguised = tmp_path / "totally_a_model.onnx"
    disguised.write_bytes(
        (FIXTURES_DIR / "malicious" / "zip_wrapped_reduce_os_system.pt").read_bytes()
    )

    assert format_from_extension(disguised) == "onnx"
    assert detect_format_from_content(disguised) == "pickle"
